// render-view — the SINGLE owner of the `docs/roadmap/ROADMAP.md` format.
//
// WHAT IT BLOCKS: the manual-snapshot failure mode DOCS.md §5 warns about and
// ADR-002/ADR-007 exist to prevent. `ROADMAP.md` carries the header "Generated
// by aidakit:roadmap — do not edit by hand; re-run to refresh." but until this
// module existed NO committed code produced that file's format: the `regen` step
// of skills/roadmap/SKILL.md described the conventions in prose and an agent
// re-derived them by hand on every run (2026-07-29, PRs #69/#70 — a throwaway
// renderer in a scratchpad). A hand-typed "generated" file can drift in format
// between two runs while claiming to be a snapshot of a live source.
//
// This is a PURE projection: derived JSON → markdown string. No fs, no git, no
// imports — the status it prints is whatever `deriveRoadmap` derived from the
// disk (ADR-002: no status is ever hand-written, here included). Being pure is
// what makes the format testable against a golden fixture, which is the leash
// that keeps a future edit from silently changing the shape of the view.
//
// Deliberately NOT a CI check: unlike a doc leash, the rendered view legitimately
// changes with the SHARED git state (an open PR flips an item to in-review), so a
// "committed file equals a fresh render" assertion would fail for reasons that
// are not drift. The fixture test pins the FORMAT; `--write` keeps the file honest.

/** H1 of the generated view. */
export const VIEW_TITLE = "# Roadmap — Now / Next / Later";

/** The do-not-edit banner. Its presence is the promise this module keeps. */
export const VIEW_HEADER = "> Generated by aidakit:roadmap — do not edit by hand; re-run to refresh.";

/** Printed under a bucket heading that has no items (never a bare heading). */
export const EMPTY_BUCKET = "_(nada planejado)_";

/**
 * The buckets, in render order. `statuses` PARTITIONS the derived status
 * vocabulary (`STATUSES` in roadmap.js) — every status must land in exactly one
 * bucket, or an item would silently vanish from a view that looks complete;
 * `renderRoadmapView` throws instead (see assertEveryStatusBucketed).
 *
 * `blocked` rides in Now: blocked work is active work that needs attention, and
 * the alternative (Later) reads as "not started". `showEpicStatus: false` in Done
 * is why a Done heading omits `— **status**`: the epic itself is usually NOT done
 * (it still has open items in Now/Later), so printing its aggregate next to a
 * list of shipped changes would read as a claim about the epic.
 */
export const BUCKETS = [
  { key: "now", heading: "## Now (in-progress / in-review)", statuses: ["in-progress", "in-review", "blocked"], showEpicStatus: true },
  { key: "next", heading: "## Next (planned)", statuses: ["planned"], showEpicStatus: true },
  { key: "later", heading: "## Later (backlog)", statuses: ["backlog"], showEpicStatus: true },
  { key: "done", heading: "## Done", statuses: ["done"], showEpicStatus: false },
];

const BUCKETED = new Set(BUCKETS.flatMap((b) => b.statuses));

/**
 * Fail-closed: a status no bucket claims would drop its item from the view
 * without a trace. Throws rather than rendering a lie.
 * @param {Array} epics
 */
function assertEveryStatusBucketed(epics) {
  const unknown = new Set();
  for (const change of eachChange(epics)) {
    if (!BUCKETED.has(change.status)) unknown.add(String(change.status));
  }
  if (unknown.size) {
    throw new Error(
      `render-view: no bucket for status ${[...unknown].sort().map((s) => `"${s}"`).join(", ")} — ` +
      "add it to BUCKETS in governance/roadmap/render-view.js (a rendered view may never silently drop an item)",
    );
  }
}

/** Walks every change of every feature of every epic, in declared order. */
function* eachChange(epics) {
  for (const epic of epics || []) {
    for (const feature of epic.features || []) {
      for (const change of feature.changes || []) yield change;
    }
  }
}

/**
 * One item line: `- <feature name> — \`<change-id>\` → <status>` plus, for a
 * shipped change whose archive dir carries a date, ` (YYYY-MM-DD)`.
 * The feature NAME (not the epic) prefixes the line because a feature is what the
 * change delivers; a feature with two change-ids yields two lines, same prefix.
 */
function renderItem(feature, change) {
  const dated = change.status === "done" && change.done_at ? ` (${change.done_at})` : "";
  return `- ${feature.name} — \`${change.id}\` → ${change.status}${dated}`;
}

/** The item lines of one epic that belong to one bucket, in declared order. */
function itemsFor(epic, bucket) {
  const lines = [];
  for (const feature of epic.features || []) {
    for (const change of feature.changes || []) {
      if (bucket.statuses.includes(change.status)) lines.push(renderItem(feature, change));
    }
  }
  return lines;
}

/**
 * Renders the Now/Next/Later view of `docs/roadmap/ROADMAP.md` from the deriver's
 * JSON (`epics` of `deriveRoadmap` / `derive-roadmap-status.js` stdout).
 *
 * Deterministic by construction: epic order is the deriver's (sorted epic
 * filenames, see collectEpics), feature and change order is the DECLARED order
 * inside the epic file, and nothing here reads a clock, the filesystem, or a
 * hash map's iteration order. Same JSON in ⇒ byte-identical string out.
 *
 * An epic appears under every bucket it has items in (with its own aggregate
 * status), and under none where it has none.
 *
 * @param {Array<{id:string, title?:string, status:string, features?:Array<{name:string, changes?:Array<{id:string, status:string, done_at?:string|null}>}>}>} epics
 * @returns {string} the full file body, ending in exactly one newline
 */
export function renderRoadmapView(epics = []) {
  assertEveryStatusBucketed(epics);
  const lines = [VIEW_TITLE, "", VIEW_HEADER, ""];
  for (const bucket of BUCKETS) {
    lines.push(bucket.heading, "");
    const groups = (epics || [])
      .map((epic) => ({ epic, items: itemsFor(epic, bucket) }))
      .filter((g) => g.items.length);
    if (!groups.length) {
      lines.push(EMPTY_BUCKET, "");
      continue;
    }
    for (const { epic, items } of groups) {
      const title = epic.title || epic.id;
      lines.push(bucket.showEpicStatus ? `### ${title} — **${epic.status}**` : `### ${title}`, "");
      lines.push(...items, "");
    }
  }
  // The file ends right after the last item line — one trailing newline, no blank line.
  while (lines.length && lines[lines.length - 1] === "") lines.pop();
  return lines.join("\n") + "\n";
}
