// Tests the ROADMAP.md renderer — the committed owner of the generated view's
// format (governance/roadmap/render-view.js). Pure Node, no framework; mirrors
// the idiom of roadmap.test.mjs (pass/fail counters, ok/eq, exit fail?1:0).
//
// WHY A GOLDEN FIXTURE: the file says "Generated by aidakit:roadmap — do not edit
// by hand" but before this renderer existed the format lived in PROSE in
// skills/roadmap/SKILL.md and an agent retyped it each regen, so it could drift
// between two runs (2026-07-29, PRs #69/#70). GOLDEN below pins the conventions
// byte-for-byte: bucket headings, `### <epic> — **<status>**` (status OMITTED in
// Done), `- <feature> — \`<id>\` → <status>` items, the `(YYYY-MM-DD)` suffix on a
// shipped item, the empty-bucket placeholder, and the exact blank-line/trailing-
// newline shape. A change to any of those fails HERE, not silently in a "snapshot".

import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";

const { renderRoadmapView, BUCKETS, VIEW_TITLE, VIEW_HEADER, EMPTY_BUCKET } =
  await import("../roadmap/render-view.js");
const { STATUSES, deriveRoadmap, deriveDoneDate } = await import("../roadmap/roadmap.js");

let pass = 0, fail = 0;
function ok(cond, name) { if (cond) pass++; else { fail++; console.log(`FAIL ${name}`); } }
function eq(a, b, name) {
  const r = JSON.stringify(a) === JSON.stringify(b);
  if (!r) console.log(`  ${name}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);
  ok(r, name);
}
/** Reports the FIRST differing line — a golden mismatch must point at the drift. */
function eqText(actual, expected, name) {
  if (actual === expected) { pass++; return; }
  fail++;
  const a = actual.split("\n"), b = expected.split("\n");
  const i = a.findIndex((l, n) => l !== b[n]);
  console.log(`FAIL ${name}`);
  console.log(`  first diff at line ${i + 1}:\n    expected: ${JSON.stringify(b[i])}\n    actual:   ${JSON.stringify(a[i])}`);
  if (a.length !== b.length) console.log(`  line count: expected ${b.length}, got ${a.length}`);
}

// ── 1. The golden fixture ────────────────────────────────
// Exercises every convention at once, including an epic that appears in THREE
// buckets (Now, Later, Done) with its aggregate status shown in two of them and
// omitted in Done, a feature carrying TWO change-ids, a done item with no dated
// archive dir (done_at null → no suffix), and an empty bucket.

const FIXTURE_EPICS = [
  {
    id: "EPIC-payments",
    title: "Payments system",
    status: "in-progress",
    features: [
      { name: "Checkout", status: "in-progress", changes: [
        { id: "feature-cart", status: "done", done_at: "2026-07-22" },
        { id: "feature-checkout-ui", status: "in-review", done_at: null },
      ] },
      { name: "Refunds", status: "in-progress", changes: [
        { id: "feature-refund", status: "in-progress", done_at: null },
      ] },
      // Two change-ids under ONE feature line → two items, same feature prefix.
      { name: "Ledger `write` path", status: "done", changes: [
        { id: "feature-ledger-a", status: "done", done_at: "2026-07-25" },
        { id: "feature-ledger-b", status: "done", done_at: null },
      ] },
      { name: "Subscriptions", status: "backlog", changes: [
        { id: "feature-subs", status: "backlog", done_at: null },
      ] },
    ],
  },
  {
    id: "EPIC-shipping",
    title: "Shipping",
    status: "backlog",
    features: [
      { name: "Rates", status: "backlog", changes: [{ id: "feature-rates", status: "backlog", done_at: null }] },
    ],
  },
  // An epic with nothing in any bucket but Done → absent from Now/Next/Later.
  {
    id: "EPIC-taxes",
    title: "Taxes",
    status: "done",
    features: [
      { name: "VAT", status: "done", changes: [{ id: "feature-vat", status: "done", done_at: "2026-07-01" }] },
    ],
  },
];

const GOLDEN = `# Roadmap — Now / Next / Later

> Generated by aidakit:roadmap — do not edit by hand; re-run to refresh.

## Now (in-progress / in-review)

### Payments system — **in-progress**

- Checkout — \`feature-checkout-ui\` → in-review
- Refunds — \`feature-refund\` → in-progress

## Next (planned)

_(nada planejado)_

## Later (backlog)

### Payments system — **in-progress**

- Subscriptions — \`feature-subs\` → backlog

### Shipping — **backlog**

- Rates — \`feature-rates\` → backlog

## Done

### Payments system

- Checkout — \`feature-cart\` → done (2026-07-22)
- Ledger \`write\` path — \`feature-ledger-a\` → done (2026-07-25)
- Ledger \`write\` path — \`feature-ledger-b\` → done

### Taxes

- VAT — \`feature-vat\` → done (2026-07-01)
`;

const rendered = renderRoadmapView(FIXTURE_EPICS);
eqText(rendered, GOLDEN, "renderRoadmapView matches the golden fixture byte-for-byte");

// Byte-level shape the golden alone would not make obvious.
ok(rendered.endsWith("→ done (2026-07-01)\n"), "ends with the last item line + exactly one newline");
ok(!rendered.endsWith("\n\n"), "no trailing blank line");
ok(rendered.split("\n")[0] === VIEW_TITLE, "line 1 is the H1 title");
ok(rendered.split("\n")[2] === VIEW_HEADER, "line 3 is the do-not-edit banner");
ok(rendered.includes(EMPTY_BUCKET), "an empty bucket prints the placeholder, never a bare heading");
// Determinism: same input ⇒ identical bytes (no clock, no fs, no map order).
ok(renderRoadmapView(FIXTURE_EPICS) === rendered, "same JSON in ⇒ byte-identical string out");

// ── 2. Bucket coverage (fail-closed) ─────────────────────
// Every derived status must land in exactly one bucket, or an item would vanish
// from a view that looks complete.
const bucketed = BUCKETS.flatMap((b) => b.statuses);
eq([...bucketed].sort(), [...STATUSES].sort(), "BUCKETS partition STATUSES exactly (no status unbucketed, none invented)");
ok(new Set(bucketed).size === bucketed.length, "no status appears in two buckets");
eq(BUCKETS.map((b) => b.key), ["now", "next", "later", "done"], "bucket render order is Now → Next → Later → Done");
ok(BUCKETS.filter((b) => b.showEpicStatus === false).map((b) => b.key).join() === "done",
  "Done is the only bucket that omits the epic's aggregate status");
// An unknown status THROWS rather than dropping the item silently.
let threw = null;
try {
  renderRoadmapView([{ id: "E", title: "E", status: "weird", features: [{ name: "F", changes: [{ id: "c", status: "weird" }] }] }]);
} catch (e) { threw = e; }
ok(threw && /no bucket for status "weird"/.test(threw.message), "an unbucketed status throws (never a silently dropped item)");

// Degenerate inputs: no epics / no features / no changes → headings + placeholders, no crash.
ok(renderRoadmapView([]).includes("## Done"), "empty epics list still renders all four buckets");
eq(renderRoadmapView([]).split("\n").filter((l) => l === EMPTY_BUCKET).length, 4, "all four buckets empty → four placeholders");
ok(renderRoadmapView([{ id: "E", title: "E", status: "backlog" }]).includes(EMPTY_BUCKET), "an epic with no features never crashes the render");
ok(renderRoadmapView([{ id: "E-no-title", status: "backlog", features: [{ name: "F", changes: [{ id: "c", status: "backlog" }] }] }])
  .includes("### E-no-title — **backlog**"), "a titleless epic falls back to its id");

// ── 3. End-to-end: disk → deriveRoadmap → render ──────────
// Proves the wiring the `regen` mode depends on, including `done_at` derived from
// the archive dir NAME (never a hand-written field, ADR-002).
const tmp = mkdtempSync(join(tmpdir(), "roadmap-view-"));
function write(rel, content) {
  const p = join(tmp, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content, "utf8");
}
// Two epic files, deliberately created in NON-alphabetical order: collectEpics
// sorts, so the rendered order must be EPIC-alpha then EPIC-zulu regardless.
write("docs/roadmap/epics/EPIC-zulu.md", [
  "# Zulu epic", "", "- **Feature:** Zeta — changes: z-one",
].join("\n"));
write("docs/roadmap/epics/EPIC-alpha.md", [
  "# Alpha epic", "", "- **Feature:** Ay — changes: a-shipped, a-open",
].join("\n"));
mkdirSync(join(tmp, "docs/archive/2026-07-11-a-shipped"), { recursive: true });
mkdirSync(join(tmp, "docs/features/a-open"), { recursive: true });

const derived = deriveRoadmap({ root: tmp });
eq(derived.epics.map((e) => e.id), ["EPIC-alpha", "EPIC-zulu"], "collectEpics sorts: epic order is filename order, not readdir order");

const e2e = renderRoadmapView(derived.epics);
eqText(e2e, [
  "# Roadmap — Now / Next / Later",
  "",
  "> Generated by aidakit:roadmap — do not edit by hand; re-run to refresh.",
  "",
  "## Now (in-progress / in-review)",
  "",
  "### Alpha epic — **in-progress**",
  "",
  "- Ay — `a-open` → in-progress",
  "",
  "## Next (planned)",
  "",
  "_(nada planejado)_",
  "",
  "## Later (backlog)",
  "",
  "### Zulu epic — **backlog**",
  "",
  "- Zeta — `z-one` → backlog",
  "",
  "## Done",
  "",
  "### Alpha epic",
  "",
  "- Ay — `a-shipped` → done (2026-07-11)",
  "",
].join("\n").replace(/\n$/, "") + "\n", "disk → deriveRoadmap → render produces the dated Done item");

// deriveDoneDate: the strict `<date>-<id>` rule.
eq(deriveDoneDate("a-shipped", { root: tmp }), "2026-07-11", "done_at comes from the archive dir's date prefix");
eq(deriveDoneDate("shipped", { root: tmp }), null, "a dir whose id merely ENDS with the query contributes no date");
eq(deriveDoneDate("a-open", { root: tmp }), null, "an unarchived change has no done_at");
eq(deriveDoneDate("g-git", { root: tmp, gitArchiveDirs: new Set(["2026-07-02-g-git"]) }), "2026-07-02",
  "a shared-git archive dir (another worktree) dates the item too");
eq(deriveDoneDate("twice", { root: tmp, gitArchiveDirs: new Set(["2026-08-09-twice", "2026-07-09-twice"]) }), "2026-07-09",
  "two archive dirs for one id resolve to the EARLIEST date, deterministically");
// An openspec archive (no date in the name) → done with no suffix, not a crash.
mkdirSync(join(tmp, "openspec/changes/archive/os-change"), { recursive: true });
eq(deriveDoneDate("os-change", { root: tmp }), null, "an undated (openspec) archive dir yields null, so the item renders without a suffix");

// ── 4. The `--write` wiring (what `regen` mode runs) ──────
const CLI = resolve(dirname(new URL(import.meta.url).pathname), "../validators/derive-roadmap-status.js");
const run = (args) => {
  const res = execFileSync("node", [CLI, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  return res;
};
const stdout = run(["--root", tmp, "--write"]);
const written = readFileSync(join(tmp, "docs/roadmap/ROADMAP.md"), "utf8");
eqText(written, e2e, "--write writes exactly the renderer's bytes into docs/roadmap/ROADMAP.md");
ok(JSON.parse(stdout).ok === true, "--write still emits the validator JSON on stdout (contract unchanged)");
ok(JSON.parse(stdout).epics[0].features[0].changes[0].done_at === "2026-07-11", "the JSON carries done_at for the renderer to consume");

// Idempotent: a second run over an unchanged tree rewrites identical bytes.
run(["--root", tmp, "--write"]);
eq(readFileSync(join(tmp, "docs/roadmap/ROADMAP.md"), "utf8"), written, "re-running --write on an unchanged tree is byte-idempotent");

// Without --write the file is left alone (the flows call this read-only).
writeFileSync(join(tmp, "docs/roadmap/ROADMAP.md"), "SENTINEL\n", "utf8");
run(["--root", tmp]);
eq(readFileSync(join(tmp, "docs/roadmap/ROADMAP.md"), "utf8"), "SENTINEL\n", "without --write the validator never touches the file");

// A repo with no declared epics: --write writes NOTHING rather than an empty shell.
const bare = mkdtempSync(join(tmpdir(), "roadmap-bare-"));
run(["--root", bare, "--write"]);
let bareWrote = true;
try { readFileSync(join(bare, "docs/roadmap/ROADMAP.md"), "utf8"); } catch { bareWrote = false; }
ok(!bareWrote, "no epics declared → --write creates no ROADMAP.md (never clobbers with an empty shell)");

// ── 5. The `--json` output contract ──────────────────────
// The CLI advertises [--json] and change artifacts invoke it; it must mean "stdout
// JSON only, nothing on stderr" — the same contract every sibling validator honors.
// `run` above discards stderr and throws on exit 1, so use a spawn that captures
// both streams and the exit code. `tmp` (seeded in §3: EPIC-alpha with a-open
// in-progress, EPIC-zulu backlog, a-shipped archived) is the fixture root here.
const jrun = (args) => {
  const r = spawnSync("node", [CLI, "--root", tmp, ...args], { encoding: "utf8" });
  return { code: r.status, stdout: r.stdout || "", stderr: r.stderr || "" };
};

// Default: JSON on stdout AND the human view on stderr.
{
  const r = jrun([]);
  ok(r.code === 0, "default: exit 0");
  ok(JSON.parse(r.stdout).validator === "aidakit.derive-roadmap-status", "default: JSON on stdout");
  ok(r.stderr.startsWith(VIEW_TITLE), "default: the render-view.js view goes to stderr");
}

// --json: byte-identical stdout, and stderr stays EMPTY (flag honored, not ignored).
{
  const plain = jrun([]);
  const r = jrun(["--json"]);
  ok(r.code === 0, "--json: exit 0");
  ok(JSON.parse(r.stdout).validator === "aidakit.derive-roadmap-status", "--json: JSON still on stdout");
  ok(r.stderr === "", "--json: nothing on stderr (view suppressed)");
  ok(r.stdout === plain.stdout, "--json: stdout byte-identical to the default run");
}

// --json composes with --strict: exit code still comes from the orphan check
// (EPIC-zulu's z-one is declared-but-backlog → orphan), view stays suppressed.
{
  const r = jrun(["--json", "--strict"]);
  ok(r.code === 1, "--json --strict: exit 1 on a declared-but-backlog change-id");
  const j = JSON.parse(r.stdout);
  ok(j.ok === false && j.orphans.length >= 1, "--json --strict: JSON reports the orphan(s)");
  ok(r.stderr === "", "--json --strict: still nothing on stderr");
}

// --json --write: the file is still written, but the stderr status line is suppressed.
{
  const r = jrun(["--json", "--write"]);
  ok(r.code === 0, "--json --write: exit 0");
  ok(r.stderr === "", "--json --write: status line suppressed on stderr");
  ok(readFileSync(join(tmp, "docs/roadmap/ROADMAP.md"), "utf8") === e2e, "--json --write: still writes the renderer's bytes");
}

// Empty roadmap + --json: no-epics view suppressed, JSON still emitted.
{
  const r = spawnSync("node", [CLI, "--root", bare, "--json"], { encoding: "utf8" });
  ok((r.stderr || "") === "", "empty roadmap + --json: nothing on stderr");
  ok(JSON.parse(r.stdout).epics_count === 0, "empty roadmap + --json: JSON still on stdout");
}

console.log(`\n${pass} passed, ${fail} failed`);
rmSync(tmp, { recursive: true, force: true });
rmSync(bare, { recursive: true, force: true });
process.exit(fail ? 1 : 0);
